# Global settings
device: "cuda"
seed: 42

# Video processing
video:
  frame_sample_rate: 1
  model_name: "prithivMLmods/Deep-Fake-Detector-v2-Model"
  batch_size: 8
  face_detection: true

# Audio processing
audio:
  model_name: "MelodyMachine/Deepfake-audio-detection-V2"
  sample_rate: 16000
  use_asr: false

# Text processing
text:
  model_name: "desklib/ai-text-detector-v1.01"
  max_length: 768
  threshold: 0.5

# FAISS retrieval
#retrieval:
#  articles_path: "data/articles.json"
#  index_path: "data/faiss_index.bin"
 # embedder_model: "all-MiniLM-L6-v2"
  #top_k: 5

# Paths
temp_dir: "data/processed"

retrieval:
  articles_path: "data/articles.json"
  index_path: "data/faiss/index.faiss"
  embedder_model: "sentence-transformers/all-MiniLM-L6-v2"
  top_k: 5
